NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror
OBJ = ft_atoi.o ft_itoa.o ft_putnbr_fd.o ft_strlcpy.o ft_tolower.o\
		ft_bzero.o ft_memchr.o ft_putstr_fd.o ft_strlen.o ft_toupper.o\
		ft_calloc.o ft_memcmp.o ft_split.o ft_strmapi.o \
		ft_isalnum.o ft_memcpy.o ft_strchr.o ft_strncmp.o \
		ft_isalpha.o ft_memmove.o ft_strdup.o ft_strnstr.o \
		ft_isascii.o ft_memset.o ft_striteri.o ft_strrchr.o\
		ft_isdigit.o ft_putchar_fd.o ft_strjoin.o ft_strtrim.o\
		ft_isprint.o ft_putendl_fd.o ft_strlcat.o ft_substr.o

RM = rm -f

AR = ar rcs

HEADER = libft.h

all : $(NAME)

$(NAME) : $(OBJ)
	$(AR) $(NAME) $(OBJ)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
